#!/usr/bin/sh

sxhkd &
picom -b &
~/.config/polybar/launch.sh &
nitrogen --restore &
wmname LG3D

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a quake state=floating
bspc rule -a exp state=floating

bspc rule -a dropdown sticky=on state=floating hidden=on
bspc rule -a obsidian sticky=on state=floating hidden=on
bspc rule -a explorer sticky=on state=floating hidden=on
kitty --class dropdown &
kitty --class explorer broot &
